### ISSUE TITLE
关于助战选择

### ISSUE THREAD

**Issue by Usigned** [SammyXue/fgo.air#1]
https://github.com/SammyXue/fgo.air/blob/9a33cc56f46fb01aa4f338b8fcdc58dd4e3fbde6/fgo.py#L389
请问选助战的时候是只扫描当前页有无特定从者，若无就刷新，没有下拉操作吗？
还有这里可以保证一定选到310的从者吗？

**Comment by SammyXue** [comment]
1.“只扫描当前页有无特定从者，若无就刷新，没有下拉操作吗” 是的
2.没有保证310

**Comment by Usigned** [comment]
ok，了解了，感谢🤝
